@startuml
hide footbox

participant "Patient Demographics Consumer" as CON
participant "Patient Demographics Supplier" as SUP

CON -> SUP :Patient Demographics Query HL7 QBP^Q22
activate SUP
SUP --> CON : Patient Demographics Response HL7 RSP^K22
deactivate SUP


@enduml