@startuml
hide footbox

participant "Document Consumer" as C
participant "Document Responder" as R

C -> R : Retrieve Document Request Message
activate R
R --> C : Retrieve Document Response Message
deactivate R


@enduml