@startuml
hide footbox

participant "Document\nRegistry" as DOC
participant "Patient Identifier\nCross-Reference Manager" as MPI

MPI -> DOC :Notify XAD-PID Link Change HL7 ADT^A43
activate DOC
DOC --> MPI : Acknowledge HL7 ADT^ACK
deactivate DOC


@enduml