@startuml
hide footbox

participant "Document Source" as S
participant "Document Recipient" as R

S -> R : Provide Document Bundle Request Message
activate R
R --> S : Provide Document Bundle Response Message
deactivate R


@enduml